version: '3.7'
services:
  api:
    image: muninn/restdemo
    ports:
      - 1328:1324
    environment:
      - CONFIGOR_ENV_PREFIX=-
      - APP_DEBUG=false
      - APP_BASEURL=https://demo.crandom.com/
      - APP_FILEURL=https://static.crandom.com/
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=demo
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  redis:
    image: redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  mysql:
    image: mysql:8
    environment:
      - TZ=Asia/Shanghai 
      - MYSQL_ROOT_PASSWORD=root 
      - MYSQL_DATABASE=demo
    volumes:
      - db-data:/var/lib/mysql 
    deploy:
      placement:
        constraints: [node.role == manager]

volumes:
  db-data:
