package main

import (
	"net/http"

	"github.com/go-redis/redis"
	_ "github.com/hyacinthus/ske/docs" // docs is generated by Swag CLI
	"github.com/hyacinthus/x/xerr"
	"github.com/hyacinthus/x/page"
	"github.com/hyacinthus/x/cc"
	"github.com/hyacinthus/x/auth"
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	"github.com/labstack/echo"
	"github.com/labstack/echo/middleware"
	"github.com/swaggo/echo-swagger"
)

// 定义全区变量 为了保证执行顺序 初始化均在main中执行
var (
	// gorm mysql db connection
	db *gorm.DB
	// redis client
	rdb *redis.Client
)

// @title RESTful API DEMO by Golang & Echo
// @version 1.0
// @description This is a demo server.

// @contact.name Muninn
// @contact.email hyacinthus@gmail.com

// @license.name MIT
// @license.url https://github.com/hyacinthus/restdemo/blob/master/LICENSE

// @host demo.crandom.com
// @BasePath /
func main() {
	// init echo
	e := echo.New()

	// error handler
	e.HTTPErrorHandler = xerr.ErrorHandler

	// common middleware
	e.Use(middleware.Logger())
	e.Use(middleware.Recover())
	e.Use(middleware.CORS())
	e.Use(page.Middleware(config.APP.PageSize)) // 分页参数解析，在 pagination.go 定义

	// Echo debug setting
	if config.APP.Debug {
		e.Debug = true
	}

	// auth group
	a := e.Group("/")
	a.Use(middleware.JWTWithConfig(middleware.JWTConfig{
		SigningKey: []byte(config.APP.JWTSecret),
		SuccessHandler: auth.ParseJWT,
	  }))

	// init mysql and redis
	initDB()
	defer db.Close()
	initRedis()
	defer rdb.Close()

	// init global cache
	cc.Init(rdb)

	// async create tables
	go createTables()

	// swagger
	e.GET("/docs/*", echoSwagger.WrapHandler)

	// status
	e.GET("/status", getStatus)

	// note Routes
	e.GET("/notes", getEntitys)
	e.POST("/notes", createEntity)
	e.GET("/notes/:id", getEntity)
	e.PUT("/notes/:id", updateEntity)
	e.DELETE("/notes/:id", deleteEntity)

	// Start echo server
	e.Logger.Fatal(e.Start(config.APP.Host + ":" + config.APP.Port))
}

// API状态 成功204 失败500
func getStatus(c echo.Context) error {
	return c.NoContent(http.StatusNoContent)
}
